import React, { useEffect, useMemo, useState } from "react";
import { DEFAULT_CATEGORIES, usePortfolio } from "../hooks/usePortfolio";
import { isSupabaseConfigured, MEDIA_BUCKET, supabase } from "../lib/supabase";

const MAX_IMAGE=20*1024*1024, MAX_VIDEO=500*1024*1024;
const emptyForm={title:"",description:"",category:"Reels",tags:"",featured:false,hero_media:false,published:true};
const safeName=name=>name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");
const whatsappNumber=value=>String(value||"").replace(/\D/g,"").replace(/^0+/,"");

export default function Admin(){
  const [session,setSession]=useState(null),[authLoading,setAuthLoading]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("work");
  const [editing,setEditing]=useState(null),[form,setForm]=useState(emptyForm),[file,setFile]=useState(null),[poster,setPoster]=useState(null),[preview,setPreview]=useState("");
  const [messages,setMessages]=useState([]),[messagesLoading,setMessagesLoading]=useState(false),[openMessage,setOpenMessage]=useState(null);
  const {items,loading,refresh}=usePortfolio({includeHidden:true});
  const categories=useMemo(()=>[...new Set([...DEFAULT_CATEGORIES,...items.map(x=>x.category).filter(Boolean)])],[items]);
  const unread=messages.filter(x=>x.status==="new").length;

  useEffect(()=>{if(!supabase){setAuthLoading(false);return;}supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const {data}=supabase.auth.onAuthStateChange((_,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>()=>preview&&URL.revokeObjectURL(preview),[preview]);
  const loadMessages=async()=>{if(!session)return;setMessagesLoading(true);const {data,error}=await supabase.from("contact_messages").select("*").order("created_at",{ascending:false});if(error)setNotice(error.message);else setMessages(data||[]);setMessagesLoading(false)};
  useEffect(()=>{if(session)loadMessages()},[session]);
  const login=async e=>{e.preventDefault();setBusy(true);setNotice("");const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setNotice(error.message)};
  const openForm=item=>{setEditing(item||null);setForm(item?{title:item.title,description:item.description,category:item.category,tags:(item.tags||[]).join(", "),featured:item.featured,hero_media:item.hero_media||false,published:item.published}:emptyForm);setFile(null);setPoster(null);setPreview("");setTab("work")};
  const validate=f=>{if(!f?.size)return"Choose a non-empty file.";const allowed=["image/jpeg","image/png","image/webp","video/mp4","video/webm"];if(!allowed.includes(f.type))return"Use JPG, PNG, WebP, MP4 or WebM. MOV is not browser-safe.";if(f.size>(f.type.startsWith("video/")?MAX_VIDEO:MAX_IMAGE))return`File is too large (maximum ${f.type.startsWith("video/")?500:20} MB).`;return""};
  const upload=async(f,folder)=>{const path=`${folder}/${crypto.randomUUID()}-${safeName(f.name)}`;const {error}=await supabase.storage.from(MEDIA_BUCKET).upload(path,f,{contentType:f.type,upsert:false});if(error)throw error;return{path,url:supabase.storage.from(MEDIA_BUCKET).getPublicUrl(path).data.publicUrl}};
  const save=async e=>{e.preventDefault();if(!editing&&!file){setNotice("Choose a photo or video.");return}const invalid=file&&validate(file);if(invalid){setNotice(invalid);return}if(poster&&!/[image]\/(jpeg|png|webp)/.test(poster.type)){setNotice("Poster must be a JPG, PNG or WebP image.");return}setBusy(true);setNotice("Uploading…");try{let media={path:editing?.media_path,url:editing?.media_url},cover={path:editing?.poster_path,url:editing?.poster_url};if(file)media=await upload(file,"work");if(poster)cover=await upload(poster,"posters");if(form.hero_media)await supabase.from("projects").update({hero_media:false}).neq("id",editing?.id||crypto.randomUUID());const payload={title:form.title.trim()||"Untitled work",description:form.description.trim(),category:form.category,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),featured:form.featured,hero_media:form.hero_media,published:form.published,media_type:file?(file.type.startsWith("video/")?"video":"image"):editing.media_type,media_url:media.url,media_path:media.path,poster_url:cover.url||null,poster_path:cover.path||null,updated_at:new Date().toISOString(),...(!editing?{display_order:items.length}:{})};const result=editing?await supabase.from("projects").update(payload).eq("id",editing.id):await supabase.from("projects").insert(payload);if(result.error)throw result.error;if(editing&&file&&editing.media_path)await supabase.storage.from(MEDIA_BUCKET).remove([editing.media_path]);if(editing&&poster&&editing.poster_path)await supabase.storage.from(MEDIA_BUCKET).remove([editing.poster_path]);setNotice("Published successfully.");openForm(null);await refresh()}catch(err){setNotice(err.message||"Upload failed.")}finally{setBusy(false)}};
  const patchItem=async(item,changes)=>{setBusy(true);if(changes.hero_media)await supabase.from("projects").update({hero_media:false}).neq("id",item.id);const {error}=await supabase.from("projects").update({...changes,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)setNotice(error.message);await refresh();setBusy(false)};
  const remove=async item=>{if(!confirm("Are you sure you want to delete this work?"))return;setBusy(true);const {error}=await supabase.from("projects").delete().eq("id",item.id);if(!error){const paths=[item.media_path,item.poster_path].filter(Boolean);if(paths.length)await supabase.storage.from(MEDIA_BUCKET).remove(paths);await refresh()}setNotice(error?.message||"Work deleted.");setBusy(false)};
  const move=async(item,delta)=>{const i=items.findIndex(x=>x.id===item.id),other=items[i+delta];if(!other)return;setBusy(true);await Promise.all([supabase.from("projects").update({display_order:other.display_order}).eq("id",item.id),supabase.from("projects").update({display_order:item.display_order}).eq("id",other.id)]);await refresh();setBusy(false)};
  const setStatus=async(message,status)=>{const {error}=await supabase.from("contact_messages").update({status}).eq("id",message.id);if(error)setNotice(error.message);else{setMessages(list=>list.map(x=>x.id===message.id?{...x,status}:x));setOpenMessage(current=>current?.id===message.id?{...current,status}:current)}};
  const deleteMessage=async message=>{if(!confirm("Are you sure you want to delete this message?"))return;const {error}=await supabase.from("contact_messages").delete().eq("id",message.id);if(error)setNotice(error.message);else{setMessages(list=>list.filter(x=>x.id!==message.id));setOpenMessage(null)}};

  if(!isSupabaseConfigured)return <main className="admin-shell"><div className="admin-login"><h1>Admin setup required</h1><p>Add values from <code>.env.example</code> and run <code>supabase/schema.sql</code>.</p></div></main>;
  if(authLoading)return <main className="admin-shell"><div className="admin-login">Loading…</div></main>;
  if(!session)return <main className="admin-shell"><form className="admin-login" onSubmit={login}><span>LUCKY FX STUDIO</span><h1>Admin Login</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="btn btn-primary" disabled={busy}>{busy?"Signing in…":"Login"}</button>{notice&&<p className="admin-notice">{notice}</p>}</form></main>;

  return <main className="admin-shell"><header className="admin-header"><div><span>LUCKY FX STUDIO</span><h1>Admin Dashboard</h1></div><div><a href={import.meta.env.BASE_URL}>View website</a><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></header>
    <nav className="admin-tabs"><button className={tab==="work"?"active":""} onClick={()=>setTab("work")}>Projects</button><button className={tab==="messages"?"active":""} onClick={()=>setTab("messages")}>Messages {unread?`(${unread})`:""}</button></nav>
    <section className="admin-panel">{notice&&<p className="admin-notice">{notice}</p>}{tab==="messages"?<><div className="admin-actions"><div><h2>Messages</h2><p>Newest inquiries first</p></div><button onClick={loadMessages}>Refresh</button></div>{messagesLoading?<p>Loading…</p>:<div className="message-list">{messages.map(message=><article key={message.id} className={`message-card ${message.status}`} onClick={()=>{setOpenMessage(message);if(message.status==="new")setStatus(message,"read")}}><div><span className="message-status">{message.status}</span><time>{new Date(message.created_at).toLocaleString()}</time></div><h3>{message.name}</h3><p>{message.service||"General inquiry"}</p><strong>{message.message}</strong></article>)}{!messages.length&&<p>No messages yet.</p>}</div>}{openMessage&&<div className="message-dialog" onClick={()=>setOpenMessage(null)}><article onClick={e=>e.stopPropagation()}><button className="message-close" onClick={()=>setOpenMessage(null)}>×</button><span className="message-status">{openMessage.status}</span><h2>{openMessage.name}</h2><p><a href={`mailto:${openMessage.email}`}>{openMessage.email}</a>{openMessage.phone&&<> · {openMessage.phone}</>}</p><small>{openMessage.service||"General inquiry"} · {new Date(openMessage.created_at).toLocaleString()}</small><blockquote>{openMessage.message}</blockquote><div className="message-actions"><a href={`mailto:${openMessage.email}?subject=${encodeURIComponent(`Re: Lucky FX ${openMessage.service||"inquiry"}`)}`}>Reply by Email</a>{whatsappNumber(openMessage.phone)&&<a href={`https://wa.me/${whatsappNumber(openMessage.phone)}`} target="_blank" rel="noreferrer">Reply on WhatsApp</a>}<button onClick={()=>setStatus(openMessage,"read")}>Mark Read</button><button onClick={()=>setStatus(openMessage,"replied")}>Mark Replied</button><button className="danger" onClick={()=>deleteMessage(openMessage)}>Delete</button></div></article></div>}</>:<>
      <div className="admin-actions"><div><h2>Your work</h2><p>{items.length} item{items.length===1?"":"s"}</p></div><button className="btn btn-primary" onClick={()=>openForm(null)}>+ ADD WORK</button></div>
      <form className="admin-editor" onSubmit={save}><h2>{editing?"Edit work":"Add work"}</h2><div className="media-type-choice"><label><input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" onChange={e=>{const f=e.target.files[0];setFile(f);setPreview(f?URL.createObjectURL(f):"")}} required={!editing}/><span>PHOTO OR VIDEO / REEL</span></label></div>{(preview||editing?.media_url)&&<div className="admin-preview">{(file?.type.startsWith("video/")||(!file&&editing?.media_type==="video"))?<video src={preview||editing.media_url} controls/>:<img src={preview||editing.media_url} alt="Preview"/>}</div>}<div className="admin-form-grid"><label>Title<input value={form.title} maxLength="120" onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Caption<textarea value={form.description} maxLength="2000" onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label>Video poster<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPoster(e.target.files[0])}/></label><label className="check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><label className="check"><input type="checkbox" checked={form.hero_media} onChange={e=>setForm({...form,hero_media:e.target.checked})}/> Hero Media</label><label className="check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label></div><div className="admin-editor-actions"><button type="button" onClick={()=>openForm(null)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?"Uploading…":"Publish"}</button></div></form>
      {loading?<p>Loading…</p>:<div className="admin-grid">{items.map((item,i)=><article key={item.id} className={!item.published?"hidden":""}>{item.media_type==="video"?<video src={item.media_url} poster={item.poster_url||undefined} preload="metadata"/>:<img src={item.media_url} alt={item.title}/>}<div><h3>{item.title}</h3><p>{item.category} · {item.published?"Published":"Hidden"}{item.hero_media?" · Hero Media":""}</p><div className="admin-item-actions"><button onClick={()=>openForm(item)}>Edit</button><button onClick={()=>patchItem(item,{published:!item.published})}>{item.published?"Hide":"Publish"}</button><button onClick={()=>patchItem(item,{hero_media:!item.hero_media})}>{item.hero_media?"Remove Hero":"Set as Hero"}</button><button disabled={i===0} onClick={()=>move(item,-1)}>↑</button><button disabled={i===items.length-1} onClick={()=>move(item,1)}>↓</button><button className="danger" onClick={()=>remove(item)}>Delete</button></div></div></article>)}</div>}</>}</section></main>;
}
